---

- name: Stop tvault-objetc-store service if running
  service: name=tvault-object-store state=stopped
  ignore_errors: yes

- name: Stop tvault-contego service if running
  service: name=tvault-contego state=stopped
  ignore_errors: yes

- name: Setup trilio yum repo for queens
  template:
     src: trilio.repo
     dest: "{{trilio_yum_repo_file_path}}"

- name: Reload Daemon
  shell: systemctl daemon-reload

- name: Install packages on compute node to install tvault-contego-extension | centos-release-openstack-{{OPENSTACK_DIST}}
  yum:
     update_cache: yes
     name:
        - "centos-release-openstack-{{OPENSTACK_DIST | lower}}"
     state: latest
  register: result

- name: install contego extension packages when using python2
  yum:
     update_cache: yes
     name:
        - puppet-triliovault
        - tvault-contego
     state: latest
  when: PYTHON_VERSION=="python2"
  
- name: install contego extension packages when using python3
  yum:
     update_cache: yes
     name:
        - puppet-triliovault
        - python3-tvault-contego
     state: latest
  when: PYTHON_VERSION=="python3"

- name: Uninstall centos-release-openstack-{{OPENSTACK_DIST}} from compute node used to install tvault-contego-extension
  yum:
     update_cache: yes
     name:
        - "centos-release-openstack-{{OPENSTACK_DIST | lower}}"
     state: absent
  when: result is succeeded
